### PR TITLE
Forth BOM

### PR DESCRIPTION
**Pull request by matteodv99tn**
Hi @AmmarkoV , I created a Markdown table from the e-mail you sent me.
I kindly ask you to check out 2 things:
1. from Mouser, that in Italy is a well known electronic component dealer, I have not been able to find the mosfet with the same exact specification as yours, even though the product code is the same. Can you check if they are fine anyway?
2. searching on the network, I found that the product that best fits your description for the 600 lumen lights is the `PWLS 05‑10` (you might see the italian webpage to buy). Can you confirm that?

I might reach you out in the next days, once I get to know the best procedure here at the university of Trento to buy all the stuff.

Thanks in advance!

### CODE REVIEW

**Comment by matteodv99tn** [comment]
Hi @AmmarkoV 
Can you check the BOM from your side and, if correct, merge the PR?

Thanks!
Matteo

**Comment by AmmarkoV** [comment]
Dear @matteodv99tn 
The MOSFET is ok,
https://www.findchips.com/compare/IRFZ44N---NXP%20Semiconductors--vs--IRFZ44NPBF---International%20Rectifier
what you find is actually improved and e-waste compliant version of the one we used, it has the same electrical characteristics

The lamp unfortunately is not the same, I tried to track the chinese serial numbers, I think this might be an equivalent to what we have :
https://scontimania.com/mini-torcia-tascabile-led-10000-lumen-torcia-ricaricabile-modalita-torcia-tattica-zoomabile-per-campeggio-escursionismo-ed-emergenze-2.html

So I guess I should not do the pull request ? since there needs to be a change ?

**Comment by matteodv99tn** [comment]
Hi @AmmarkoV , thanks for the reply
I update the link with the one you reported.

Checking the italian website you suggested, the lamps appear to have a light flux of 400lm, rather then the 600lm you have. Could that be an issue in the final implementation?

**Comment by AmmarkoV** [comment]
@matteodv99tn  
The luminosity of the lamp is controlled based on the current flowing to the LED, so a 800 or 600 or 400 lumens LED can in principle be tuned using a potentiometer to emmit similarly. I am more concerned about the form factor. I bought these lamps because they have an assembly a heatsink a reflector a plexiglass "lens" to apply the polarizer on and everything sorted out to make it easier to assemble them. The previous one you sent seems to have a different form factor, this one looks "visually" more like the ones we have :S . I will now upload some OpenSCAD/STL files to see the planned camera assembly

**Comment by AmmarkoV** [comment]
@matteodv99tn  
This is current design for the camera 
https://github.com/magician-project/magician-project/blob/FORTH-BOM/CAD/camerav2.stl

Its written in OpenSCAD ( https://openscad.org/ )
and the source code is this, by commenting in and out the last lines you can render / 3D print specific parts of it
https://github.com/magician-project/magician-project/blob/FORTH-BOM/CAD/camerav2.scad

Is Nikos Tsagkarakis in the repository ? 
What is his username so I can also tag him because I think they might be useful to him as well

**Comment by matteodv99tn** [comment]
Thank you for the explanation, I didn't thought on controlling the light intensity simply by changing the current. So as long as the form factor is the same, there's no problem.

Nikos himself is not part of the GitHub organisation, however you can ping all people at IIT with @magician-project/iit-hhcm . Guys, please see the linked CAD file when considering the envelope of the vision system.

In the mean time, I'll merge the PR. If you need to add any change, just create yourself a new branch and create a pull request whenever you want!

**Pull request merged**
